[32mINFO    [0m test_valid_login_006:Test_Login.py:92 Testcase_001_validate the Login with valid credentials